services:
  frontend:
    build: ./frontend
    container_name: thulasi-frontend
    expose:
      - "80"
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

  backend:
    build: ./backend
    container_name: thulasi-backend
    expose:
      - "3000"
    environment:
      PORT: 3000
      AWS_REGION: ap-south-1
      DYNAMODB_TABLE: ThulasiTable
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
